//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:46+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class Point32 : IMessage
    {
        ///<exclude/>
        public Point32()
        {
        }
        ///<exclude/>
        public Point32(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public float x { get; set; }
        ///<exclude/>
        public float y { get; set; }
        ///<exclude/>
        public float z { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/Point32"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "cc153912f1453b708d221682bc23d9ac"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "float32 x\nfloat32 y\nfloat32 z"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return false; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            bw.Write(x);
            bw.Write(y);
            bw.Write(z);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            x = br.ReadSingle();
            y = br.ReadSingle();
            z = br.ReadSingle();
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return 4 + 4 + 4; }
        }
        ///<exclude/>
        public bool Equals(Point32 other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.x.Equals(x) && other.y.Equals(y) && other.z.Equals(z);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(Point32)) return false;
            return Equals((Point32)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ x.GetHashCode();
                result = (result * 397) ^ y.GetHashCode();
                result = (result * 397) ^ z.GetHashCode();
                return result;
            }
        }
    }
}
