//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:47+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class PointStamped : IMessage
    {
        ///<exclude/>
        public PointStamped()
        {
            header = new Header();
            point = new Point();
        }
        ///<exclude/>
        public PointStamped(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public Point point { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/PointStamped"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "c63aecb41bfdfd6b7e1fac37c7cbe7bf"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nPoint point"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            point.Serialize(bw);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            point = new Point(br);
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + point.SerializeLength; }
        }
        ///<exclude/>
        public bool Equals(PointStamped other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.point.Equals(point);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(PointStamped)) return false;
            return Equals((PointStamped)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ point.GetHashCode();
                return result;
            }
        }
    }
}
