//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:47+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class PolygonStamped : IMessage
    {
        ///<exclude/>
        public PolygonStamped()
        {
            header = new Header();
            polygon = new Polygon();
        }
        ///<exclude/>
        public PolygonStamped(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public Polygon polygon { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/PolygonStamped"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "c6be8f7dc3bee7fe9e8d296070f53340"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nPolygon polygon"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            polygon.Serialize(bw);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            polygon = new Polygon(br);
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + polygon.SerializeLength; }
        }
        ///<exclude/>
        public bool Equals(PolygonStamped other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.polygon.Equals(polygon);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(PolygonStamped)) return false;
            return Equals((PolygonStamped)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ polygon.GetHashCode();
                return result;
            }
        }
    }
}
