//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:47+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class Pose2D : IMessage
    {
        ///<exclude/>
        public Pose2D()
        {
        }
        ///<exclude/>
        public Pose2D(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public double x { get; set; }
        ///<exclude/>
        public double y { get; set; }
        ///<exclude/>
        public double theta { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/Pose2D"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "938fa65709584ad8e77d238529be13b8"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "float64 x\nfloat64 y\nfloat64 theta"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return false; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            bw.Write(x);
            bw.Write(y);
            bw.Write(theta);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            x = br.ReadDouble();
            y = br.ReadDouble();
            theta = br.ReadDouble();
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return 8 + 8 + 8; }
        }
        ///<exclude/>
        public bool Equals(Pose2D other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.x.Equals(x) && other.y.Equals(y) && other.theta.Equals(theta);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(Pose2D)) return false;
            return Equals((Pose2D)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ x.GetHashCode();
                result = (result * 397) ^ y.GetHashCode();
                result = (result * 397) ^ theta.GetHashCode();
                return result;
            }
        }
    }
}
