//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:47+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class PoseArray : IMessage
    {
        ///<exclude/>
        public PoseArray()
        {
            header = new Header();
            poses = new List<Pose>();
        }
        ///<exclude/>
        public PoseArray(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public List<Pose> poses { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/PoseArray"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "916c28c5764443f268b296bb671b9d97"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nPose[] poses"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            bw.Write(poses.Count); for(int i=0; i<poses.Count; i++) { poses[i].Serialize(bw);}
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            poses = new List<Pose>(br.ReadInt32()); for(int i=0; i<poses.Capacity; i++) { var x = new Pose(br);poses.Add(x);}
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + 4 + poses.Sum(x => x.SerializeLength); }
        }
        ///<exclude/>
        public bool Equals(PoseArray other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.poses.SequenceEqual(poses);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(PoseArray)) return false;
            return Equals((PoseArray)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ poses.GetHashCode();
                return result;
            }
        }
    }
}
