//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:47+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class PoseWithCovariance : IMessage
    {
        ///<exclude/>
        public PoseWithCovariance()
        {
            pose = new Pose();
            covariance = new double[36];
        }
        ///<exclude/>
        public PoseWithCovariance(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Pose pose { get; set; }
        ///<exclude/>
        public double[] covariance { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/PoseWithCovariance"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "c23e848cf1b7533a8d7c259073a97e6f"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Pose pose\nfloat64[36] covariance"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return false; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            pose.Serialize(bw);
            for(int i=0; i<36; i++) { bw.Write(covariance[i]);}
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            pose = new Pose(br);
            for(int i=0; i<36; i++) { covariance[i] = covariance[i] = br.ReadDouble();}
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return pose.SerializeLength + covariance.Sum(x => 8); }
        }
        ///<exclude/>
        public bool Equals(PoseWithCovariance other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.pose.Equals(pose) && other.covariance.SequenceEqual(covariance);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(PoseWithCovariance)) return false;
            return Equals((PoseWithCovariance)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ pose.GetHashCode();
                result = (result * 397) ^ covariance.GetHashCode();
                return result;
            }
        }
    }
}
