//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:47+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class PoseStamped : IMessage
    {
        ///<exclude/>
        public PoseStamped()
        {
            header = new Header();
            pose = new Pose();
        }
        ///<exclude/>
        public PoseStamped(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public Pose pose { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/PoseStamped"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "d3812c3cbc69362b77dc0b19b345f8f5"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nPose pose"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            pose.Serialize(bw);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            pose = new Pose(br);
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + pose.SerializeLength; }
        }
        ///<exclude/>
        public bool Equals(PoseStamped other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.pose.Equals(pose);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(PoseStamped)) return false;
            return Equals((PoseStamped)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ pose.GetHashCode();
                return result;
            }
        }
    }
}
