//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:48+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class QuaternionStamped : IMessage
    {
        ///<exclude/>
        public QuaternionStamped()
        {
            header = new Header();
            quaternion = new Quaternion();
        }
        ///<exclude/>
        public QuaternionStamped(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public Quaternion quaternion { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/QuaternionStamped"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "e57f1e547e0e1fd13504588ffc8334e2"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nQuaternion quaternion"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            quaternion.Serialize(bw);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            quaternion = new Quaternion(br);
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + quaternion.SerializeLength; }
        }
        ///<exclude/>
        public bool Equals(QuaternionStamped other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.quaternion.Equals(quaternion);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(QuaternionStamped)) return false;
            return Equals((QuaternionStamped)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ quaternion.GetHashCode();
                return result;
            }
        }
    }
}
