//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:48+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class TransformStamped : IMessage
    {
        ///<exclude/>
        public TransformStamped()
        {
            header = new Header();
            child_frame_id = string.Empty;
            transform = new Transform();
        }
        ///<exclude/>
        public TransformStamped(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public string child_frame_id { get; set; }
        ///<exclude/>
        public Transform transform { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/TransformStamped"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "b5764a33bfeb3588febc2682852579b0"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nstring child_frame_id\nTransform transform"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            bw.WriteUtf8String(child_frame_id);
            transform.Serialize(bw);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            child_frame_id = br.ReadUtf8String();
            transform = new Transform(br);
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + 4 + child_frame_id.Length + transform.SerializeLength; }
        }
        ///<exclude/>
        public bool Equals(TransformStamped other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.child_frame_id.Equals(child_frame_id) && other.transform.Equals(transform);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(TransformStamped)) return false;
            return Equals((TransformStamped)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ child_frame_id.GetHashCode();
                result = (result * 397) ^ transform.GetHashCode();
                return result;
            }
        }
    }
}
