//----------------------------------------------------------------
// <auto-generated>
//     This code was generated by the GenMsg. Version: 0.1.0.0
//     Don't change it manually.
//     2015-02-02T21:01:49+09:00
// </auto-generated>
//----------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using RosSharp.Message;
using RosSharp.Service;
using RosSharp.std_msgs;
namespace RosSharp.geometry_msgs
{
    ///<exclude/>
    public class WrenchStamped : IMessage
    {
        ///<exclude/>
        public WrenchStamped()
        {
            header = new Header();
            wrench = new Wrench();
        }
        ///<exclude/>
        public WrenchStamped(BinaryReader br)
        {
            Deserialize(br);
        }
        ///<exclude/>
        public Header header { get; set; }
        ///<exclude/>
        public Wrench wrench { get; set; }
        ///<exclude/>
        public string MessageType
        {
            get { return "geometry_msgs/WrenchStamped"; }
        }
        ///<exclude/>
        public string Md5Sum
        {
            get { return "d78d3cb249ce23087ade7e7d0c40cfa7"; }
        }
        ///<exclude/>
        public string MessageDefinition
        {
            get { return "Header header\nWrench wrench"; }
        }
        ///<exclude/>
        public bool HasHeader
        {
            get { return true; }
        }
        ///<exclude/>
        public void Serialize(BinaryWriter bw)
        {
            header.Serialize(bw);
            wrench.Serialize(bw);
        }
        ///<exclude/>
        public void Deserialize(BinaryReader br)
        {
            header = new Header(br);
            wrench = new Wrench(br);
        }
        ///<exclude/>
        public int SerializeLength
        {
            get { return header.SerializeLength + wrench.SerializeLength; }
        }
        ///<exclude/>
        public bool Equals(WrenchStamped other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;
            return other.header.Equals(header) && other.wrench.Equals(wrench);
        }
        ///<exclude/>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != typeof(WrenchStamped)) return false;
            return Equals((WrenchStamped)obj);
        }
        ///<exclude/>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = 0;
                result = (result * 397) ^ header.GetHashCode();
                result = (result * 397) ^ wrench.GetHashCode();
                return result;
            }
        }
    }
}
